# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94d23dc883e786d23425572d1e61465489e5d0b43755f9975cb49ce8070221f7f441226736ac923a67e769cb650b7fde3be81c8af9f7f38b23d7689f5f7f031c

test:
  secret_key_base: 640ce4cd427e21208903f63f5082cbabf11516f6d044b6014b8b5e52d07bcbcc76214b6a15e538a3939aa75ff54f85c19506dd302be914167dea0bef88783a05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
